spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school_admin #?createDatabaseIfNotExist=true
    username: root # Username of the database to execute DML scripts (if different).
    password: root # Password of the database to execute DML scripts (if different).
  jpa:
    show-sql: true # Whether to enable logging of SQL statements.
    hibernate:
      ddl-auto: validate # DDL mode. This is actually a shortcut for the "hibernate.hbm2ddl.auto" property. Defaults to "create-drop" when using an embedded database and no schema manager was detected. Otherwise, defaults to "none".
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
